### ISSUE TITLE
Plans to publish new release?

### ISSUE THREAD

**Issue by brentezerc** [genesys/mollitia#13]
Hello! Former Genesys employee here -

Love this library and used it at Genesys and now using it in my current work. There's been some nice improvements in recent months that haven't made it into an npm release. Are there any plans to make a new release soon?

Thanks!

**Comment by cadgerfeast** [comment]
Hey @brentezerc,

Thanks a lot for using it!
I just published a new version with @tichon29's work on new retry capabilities.
This is available as `mollitia@0.1.0`: https://github.com/genesys/mollitia/releases/tag/0.1.0

Hope it suits your needs!

**Comment by brentezerc** [comment]
@cadgerfeast Thank you so much!
