### ISSUE TITLE
enhancement: the possibility to add the mane of module that recjects the promise.

### ISSUE THREAD

**Issue by nicob-29** [genesys/mollitia#4]
For example:
I create a circuit with two modules RateLimit.
When the circuit rejects the promise related to conditon of one of modules. It is not possible to determine which module rejects the promise.

ModuleOptions allows to define a name and interface Error contains already the property name.

`export declare abstract class ModuleOptions {
    name?: string;
    active?: boolean;
    logger?: Logger;
}`

`interface Error {
    name: string;
    message: string;
    stack?: string;
}`

Is it possible to provide the name of module on RatelimitError

**Comment by cadgerfeast** [comment]
Hi @nicob-29,
Great enhancement, the pull request has a minor CI issue with sonar, we will merge this and fix the issue.
A new npm version will be available soon.

**Comment by cadgerfeast** [comment]
@nicob-29, the version has been published.
You can now install `mollitia@0.0.4`, it should contain your enhancement.
