### ISSUE TITLE
Rate Limit is not working.

### ISSUE THREAD

**Issue by CadmanEdwards** [genesys/mollitia#8]
Hi, I tested this feature in simple index.html file and used CDN for it. But its not working.

**Comment by cadgerfeast** [comment]
Hi @CadmanEdwards,
Could you copy the `index.html` file you used as a comment here?
We can have a look at it to check if there is an issue in the code, or in mollitia side.

**Comment by CadmanEdwards** [comment]
Hi, thanks for reply. can you please mention? how you are testing the rate limit.

**Comment by CadmanEdwards** [comment]
Let me tell you the scenario mentioned below.

I want to send ten (10) request to the server at a time after every 5 secs. 

Currently we are doing manually using Interval function. Now we want to use your library (mollitia.js) for this scenario.

your cooperate is highly appreciated.

Warm Regards

**Comment by cadgerfeast** [comment]
The purpose of the `Ratelimit` module is to block operations when attempting to make "bursts" of requests.
If you get blocked, you get a `RatelimitError` exception, that contains a helpful property: `remainingTimeInRatelimit`, that let you know when you will be able to make another request.

You can get the value like this:
``` javascript
for (let i = 0; i < 5; i++) {
  try {
    await myCircuit.fn(myFunction).execute('my super message');
  } catch (err) {
    console.info(`I can make a new request in ${err.remainingTimeInRatelimit}ms.`);
  }
}
```

With this, you would know when you can execute the request again.
Does that help?

**Comment by CadmanEdwards** [comment]
can I use (retry module) with rate limit?

**Comment by CadmanEdwards** [comment]
Response awaited

**Comment by cadgerfeast** [comment]
Hi @CadmanEdwards,
Indeed, the retry module can be used for this use-case, I made a little snippet that uses the Retry and Ratelimit module together to manage your needs. You can copy this snippet inside the script block from your HTML file.

``` javascript
// Time between every request (minimum)
const intervalTime = 5000;
const Mollitia = window.Mollitia;
const myRatelimit = new Mollitia.Ratelimit({
  limitPeriod: intervalTime,
  limitForPeriod: 1
});
const myRetry = new Mollitia.Retry({
  attempts: 1,
  interval: intervalTime,
  onRejection: (err) => {
    if (err instanceof Mollitia.RatelimitError) {
      return err.remainingTimeInRatelimit;
    } else {
      return false;
    }
  }
});
const myFunction = (msg) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      console.info(`${new Date().toLocaleTimeString()} - ${msg}`);
      resolve();
    }, 100);
  });
};
const myCircuit = new Mollitia.Circuit({
  func: myFunction,
  options: {
    modules: [
      myRetry,
      myRatelimit
    ]
  }
});
(async () => {
  for (let i = 0; i < 10; i++) {
    try {
      await myCircuit.fn(myFunction).execute('my super message');
    } catch (err) {
      console.info(`I can make a new request in ${err.remainingTimeInRatelimit}ms.`);
    }
  }
})();
```

Will this work for your particuliar use-case?

**Comment by CadmanEdwards** [comment]
Thanks, Let me check

**Comment by cadgerfeast** [comment]
Hi again @CadmanEdwards,

Did you have time to have a look?
Should I consider this issue as fixed?

Regards.

**Comment by CadmanEdwards** [comment]
Yes this is fixed. Thanks for your reponse.
