### ISSUE TITLE
Request for backoff templates

### ISSUE THREAD

**Issue by johnib** [genesys/mollitia#9]
Hi,

Currently the retry policy supports linear retry policy only, unless I decide on the backoff delay myself in the `onRejection` hook.
While this works, it's inconvenient and requires me to implement myself the various backoff policies.

Since this library is inspired by Polly, I'd be happy if you add this as well :)

**Comment by tichon29** [comment]
Thanks for sharing this issue @johnib
backoff policies looks like a nice piece to be added to the retry module.

**Comment by cadgerfeast** [comment]
Hi @johnib ,
They are several backoff behaviors that could be implemented using the `onRejection` hook.
Here is a code snippet of some:
``` javascript
new Retry({
  attempts: 4,
  interval: 100,
  // Constant - default [100, 100, 100, 100]
  onRejection (err, attempt) { return this.interval; },
  // Constant - first fast [0, 100, 100, 100]
  onRejection (err, attempt) { return (attempt === 0) ? 0 : this.interval; },
  // Linear [100, 200, 300, 400]
  onRejection (err, attempt) { return this.interval + (attempt * this.interval) },
  // Exponential [100, 200, 400, 800]
  onRejection (err, attempt) { return this.interval * Math.pow(2, attempt); }
})
```
Could you explain a bit what are your use-cases, and what would be your preferred API?

**Comment by johnib** [comment]
Hey,

I know it's possible, but look at what Polly does with their templates, you don't have to implement the retry logic, you just have simple notches to tweak the implementation to your flavor. 

Would you really want to implement the complex retry policy that Polly offers? Decorrelated V2
